# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to central

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - target: publishAllPublicationsToMavenCentralRepository
            os: macos-latest
          #- target: publishAndroidReleasePublicationToMavenCentralRepository
          #  os: ubuntu-latest
         # - target: publishDesktopPublicationToMavenCentralRepository
          #  os: ubuntu-latest
         # - target: publishLinuxX64PublicationToMavenCentralRepository
         #   os: ubuntu-latest
         # - target: publishKotlinMultiplatformPublicationToMavenCentralRepository
          #  os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: publish
      run: ./gradlew publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
    - name: Gradle publish
      uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
      with:
        arguments: |
          ${{ matrix.target }}
          -Psigning.gnupg.passphrase='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}'
          -Psigning.gnupg.keyName='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'
          -PmavenCentralUsername='${{secrets.OSSRH_USERNAME}}'
          -PmavenCentralPassword='${{secrets.OSSRH_PASSWORD}}'
          -Psigning.keyId='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'
          -Psigning.password='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}'
          -Psigning.secretKeyRingFile='/Users/runner/.gnupg/secring.kbx'
